### ISSUE TITLE
New version breaks display of national weather service on desktop.

### ISSUE THREAD

**Issue by aredon** [pkissling/clock-weather-card#287]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser
- [X] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
2.1.6

**Last working release (if known):**
2.1.3

**Browser and Operating System:**
Chrome, Windows 10

**Description of problem:**
Card does not display when set to national weather service. Other service providers appear to render fine. Card briefly renders without bars if navigating to another dashboard and then back several times. Issue persists in Firefox as well but not the mobile app. 

![image](https://github.com/pkissling/clock-weather-card/assets/1328757/817bbe1d-4d55-47e9-8f29-6bd406db003b)
![image](https://github.com/pkissling/clock-weather-card/assets/1328757/0f345bef-c7e6-41d4-9733-e36f8daadb33)
![image](https://github.com/pkissling/clock-weather-card/assets/1328757/d94ec9ef-f596-401c-b37b-17eb7d487b9b)

**Javascript errors shown in the web inspector (if applicable):**

```
Logger: frontend.js.latest.202310302
Source: components/system_log/__init__.py:300
First occurred: 9:39:39 PM (8 occurrences)
Last logged: 10:06:13 PM

Uncaught error from Chrome 119.0.0.0 on Windows 10 Error: Weather entity "weather.klnk_daynight" does not support daily forecasts. Ka.subscribeForecastEvents (/hacsfiles/clock-weather-card/clock-weather-card.js:243:6778) Ka.connectedCallback (/hacsfiles/clock-weather-card/clock-weather-card.js:197:75) apply (src/scoped-custom-element-registry.js:248:41) document.createElement (src/panels/lovelace/hui-root.ts:949:9) this._navigateToView (src/panels/lovelace/hui-root.ts:670:33)
Uncaught error from Chrome 119.0.0.0 on Windows 10 Error: Weather entity "weather.klnk_daynight" does not support daily forecasts. Ka.subscribeForecastEvents (/hacsfiles/clock-weather-card/clock-weather-card.js:243:6778) Ka.connectedCallback (/hacsfiles/clock-weather-card/clock-weather-card.js:197:75) apply (src/scoped-custom-element-registry.js:248:41) _addCardToColumn (src/panels/lovelace/views/hui-masonry-view.ts:277:15) Promise.all (src/panels/lovelace/views/hui-masonry-view.ts:250:11)
Uncaught error from Firefox 120.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "action-handler-clock-weather" has already been used with this registry 87659/</window.CustomElementRegistry.prototype.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/clock-weather-card/clock-weather-card.js:175:2314
Uncaught error from Firefox 120.0 on Windows 10 Error: Weather entity "weather.klnk_daynight" does not support daily forecasts. subscribeForecastEvents (/hacsfiles/clock-weather-card/clock-weather-card.js:243:6778) connectedCallback (/hacsfiles/clock-weather-card/clock-weather-card.js:197:75) apply (src/scoped-custom-element-registry.js:248:41) document.createElement (src/panels/lovelace/hui-root.ts:949:9) this._navigateToView (src/panels/lovelace/hui-root.ts:670:33)
```

**Additional information:**

**Comment by pkissling** [comment]
hi there, to reproduce the problem i wanted to create a weather entity from national weather service. upon creation, the entity is `unavailable`. can you post the data you see in your developer tools for `weather.klnk_daynight`?
<img width="1433" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/33731393/a1219186-652f-4511-abe9-aebb69d45fde">

**Comment by phurth** [comment]
I am seeing the same issue with the same error being logged regarding the weather entity not supporting daily forecasts. This was working with 2.1.3 and broke after upgrading to 2.1.6. Here are the attributes from my weather entity:
```
temperature: 32
temperature_unit: °F
humidity: 86
pressure: 29.93
pressure_unit: inHg
wind_bearing: 30
wind_speed: 10.29
wind_speed_unit: mph
visibility: 10
visibility_unit: mi
precipitation_unit: in
forecast: 
- detailed_description: >-
    A chance of rain and snow showers after 2pm. Cloudy, with a high near 35.
    Northeast wind 10 to 15 mph. Chance of precipitation is 30%.
  datetime: '2023-12-01T07:00:00-06:00'
  precipitation_probability: 30
  is_daytime: true
  condition: snowy
  wind_bearing: 45
  temperature: 35
  dew_point: 31
  wind_speed: 12.5
  humidity: 92
- detailed_description: >-
    Snow showers likely before 4am. Cloudy, with a low around 32. Northeast wind
    5 to 10 mph. Chance of precipitation is 60%. Little or no snow accumulation
    expected.
  datetime: '2023-12-01T18:00:00-06:00'
  precipitation_probability: 60
  is_daytime: false
  condition: snowy
  wind_bearing: 45
  temperature: 32
  dew_point: 32
  wind_speed: 7.5
  humidity: 100
- detailed_description: Cloudy, with a high near 37. Northeast wind 5 to 10 mph.
  datetime: '2023-12-02T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 45
  temperature: 37
  dew_point: 34
  wind_speed: 7.5
  humidity: 100
- detailed_description: >-
    A chance of rain between midnight and 3am, then a chance of rain and snow.
    Cloudy, with a low around 34. East wind around 5 mph. Chance of
    precipitation is 50%. New rainfall amounts less than a tenth of an inch
    possible.
  datetime: '2023-12-02T18:00:00-06:00'
  precipitation_probability: 50
  is_daytime: false
  condition: snowy
  wind_bearing: 90
  temperature: 34
  dew_point: 35
  wind_speed: 5
  humidity: 100
- detailed_description: >-
    Rain and snow likely. Cloudy, with a high near 36. Northeast wind 5 to 10
    mph. Chance of precipitation is 70%. New rainfall amounts between a tenth
    and quarter of an inch possible.
  datetime: '2023-12-03T06:00:00-06:00'
  precipitation_probability: 70
  is_daytime: true
  condition: snowy
  wind_bearing: 45
  temperature: 36
  dew_point: 36
  wind_speed: 7.5
  humidity: 100
- detailed_description: >-
    A slight chance of rain and snow before midnight. Mostly cloudy, with a low
    around 26. Northwest wind around 10 mph. Chance of precipitation is 20%.
  datetime: '2023-12-03T18:00:00-06:00'
  precipitation_probability: 20
  is_daytime: false
  condition: snowy
  wind_bearing: 315
  temperature: 26
  dew_point: 33
  wind_speed: 10
  humidity: 100
- detailed_description: Partly sunny, with a high near 36. West wind around 10 mph.
  datetime: '2023-12-04T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 270
  temperature: 36
  dew_point: 30
  wind_speed: 10
  humidity: 96
- detailed_description: >-
    A chance of rain and snow. Mostly cloudy, with a low around 28. Southwest
    wind 5 to 10 mph. Chance of precipitation is 40%. New snow accumulation of
    less than half an inch possible.
  datetime: '2023-12-04T18:00:00-06:00'
  precipitation_probability: 40
  is_daytime: false
  condition: snowy
  wind_bearing: 225
  temperature: 28
  dew_point: 31
  wind_speed: 7.5
  humidity: 100
- detailed_description: >-
    A chance of rain and snow. Mostly cloudy, with a high near 35. Chance of
    precipitation is 30%.
  datetime: '2023-12-05T06:00:00-06:00'
  precipitation_probability: 30
  is_daytime: true
  condition: snowy
  wind_bearing: 315
  temperature: 35
  dew_point: 32
  wind_speed: 12.5
  humidity: 100
- detailed_description: Mostly cloudy, with a low around 25.
  datetime: '2023-12-05T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: cloudy
  wind_bearing: 0
  temperature: 25
  dew_point: 31
  wind_speed: 12.5
  humidity: 96
- detailed_description: Partly sunny, with a high near 35.
  datetime: '2023-12-06T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 270
  temperature: 35
  dew_point: 28
  wind_speed: 10
  humidity: 92
- detailed_description: >-
    A slight chance of snow before midnight. Mostly cloudy, with a low around
    29. Chance of precipitation is 20%.
  datetime: '2023-12-06T18:00:00-06:00'
  precipitation_probability: 20
  is_daytime: false
  condition: snowy
  wind_bearing: 225
  temperature: 29
  dew_point: 29
  wind_speed: 12.5
  humidity: 88
- detailed_description: Partly sunny, with a high near 41.
  datetime: '2023-12-07T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 225
  temperature: 41
  dew_point: 34
  wind_speed: 15
  humidity: 92
- detailed_description: Mostly cloudy, with a low around 31.
  datetime: '2023-12-07T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: cloudy
  wind_bearing: 270
  temperature: 31
  dew_point: 33
  wind_speed: 12.5
  humidity: 92

attribution: Data from National Weather Service/NOAA
friendly_name: KETB Daynight
supported_features: 6
```

**Comment by pkissling** [comment]
can you please update to 2.1.8? this should fix the problem

**Comment by phurth** [comment]
In a separate Home Assistant install I am still getting the same error and the forecast is not rendering after updating to 2.1.8. In this case, the weather entity is set via the HA API, but is otherwise the same NWS weather object. This also worked just fine on 2.1.3. Below I'm including the attributes first from weather.kimt_daynight, then from weather.custom_location which is set to the value of the first via the API. They should be identical, but using weather.custom_location in the clock weather card no longer works.
```
temperature: 35
temperature_unit: °F
humidity: 54
pressure: 30.07
pressure_unit: inHg
wind_bearing: 110
wind_speed: 3.36
wind_speed_unit: mph
visibility: 10
visibility_unit: mi
precipitation_unit: in
forecast: 
- detailed_description: >-
    Partly sunny. High near 35, with temperatures falling to around 30 in the
    afternoon. East southeast wind around 3 mph.
  datetime: '2023-12-02T14:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 112.5
  temperature: 35
  dew_point: 24
  wind_speed: 3
  humidity: 78
- detailed_description: Mostly cloudy, with a low around 25. East northeast wind around 5 mph.
  datetime: '2023-12-02T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: cloudy
  wind_bearing: 67.5
  temperature: 25
  dew_point: 27
  wind_speed: 5
  humidity: 100
- detailed_description: >-
    A chance of snow before 5pm. Cloudy. High near 32, with temperatures falling
    to around 30 in the afternoon. North northeast wind 5 to 8 mph. Chance of
    precipitation is 50%. New snow accumulation of less than one inch possible.
  datetime: '2023-12-03T06:00:00-06:00'
  precipitation_probability: 50
  is_daytime: true
  condition: snowy
  wind_bearing: 22.5
  temperature: 32
  dew_point: 28
  wind_speed: 6.5
  humidity: 96
- detailed_description: Mostly cloudy, with a low around 22. North northwest wind around 5 mph.
  datetime: '2023-12-03T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: cloudy
  wind_bearing: 337.5
  temperature: 22
  dew_point: 26
  wind_speed: 5
  humidity: 100
- detailed_description: Mostly sunny, with a high near 37. West wind around 6 mph.
  datetime: '2023-12-04T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: partlycloudy
  wind_bearing: 270
  temperature: 37
  dew_point: 24
  wind_speed: 6
  humidity: 98
- detailed_description: >-
    A chance of snow showers. Mostly cloudy, with a low around 23. Chance of
    precipitation is 30%.
  datetime: '2023-12-04T18:00:00-06:00'
  precipitation_probability: 30
  is_daytime: false
  condition: snowy
  wind_bearing: 135
  temperature: 23
  dew_point: 25
  wind_speed: 6
  humidity: 100
- detailed_description: Mostly cloudy, with a high near 37.
  datetime: '2023-12-05T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 0
  temperature: 37
  dew_point: 28
  wind_speed: 8
  humidity: 98
- detailed_description: Mostly cloudy, with a low around 23.
  datetime: '2023-12-05T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: cloudy
  wind_bearing: 315
  temperature: 23
  dew_point: 26
  wind_speed: 9
  humidity: 94
- detailed_description: >-
    A slight chance of snow showers after noon. Mostly cloudy, with a high near
    36.
  datetime: '2023-12-06T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: snowy
  wind_bearing: 247.5
  temperature: 36
  dew_point: 25
  wind_speed: 10
  humidity: 93
- detailed_description: >-
    A slight chance of snow showers before midnight. Mostly cloudy, with a low
    around 26.
  datetime: '2023-12-06T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: snowy
  wind_bearing: 202.5
  temperature: 26
  dew_point: 28
  wind_speed: 12
  humidity: 97
- detailed_description: Partly sunny, with a high near 41.
  datetime: '2023-12-07T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 180
  temperature: 41
  dew_point: 32
  wind_speed: 9
  humidity: 96
- detailed_description: Mostly cloudy, with a low around 28.
  datetime: '2023-12-07T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: cloudy
  wind_bearing: 225
  temperature: 28
  dew_point: 31
  wind_speed: 10
  humidity: 100
- detailed_description: Mostly cloudy, with a high near 41.
  datetime: '2023-12-08T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 270
  temperature: 41
  dew_point: 36
  wind_speed: 12
  humidity: 100
- detailed_description: A slight chance of rain showers. Mostly cloudy, with a low around 28.
  datetime: '2023-12-08T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: rainy
  wind_bearing: 315
  temperature: 28
  dew_point: 33
  wind_speed: 13
  humidity: 100

attribution: Data from National Weather Service/NOAA
friendly_name: KIMT Daynight
supported_features: 6
```
```
temperature: 35
temperature_unit: °F
humidity: 54
pressure: 30.07
pressure_unit: inHg
wind_bearing: 110
wind_speed: 3.36
wind_speed_unit: mph
visibility: 10
visibility_unit: mi
precipitation_unit: in
forecast: 
- detailed_description: >-
    Partly sunny. High near 35, with temperatures falling to around 30 in the
    afternoon. East southeast wind around 3 mph.
  datetime: '2023-12-02T14:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 112.5
  temperature: 35
  dew_point: 24
  wind_speed: 3
  humidity: 78
- detailed_description: Mostly cloudy, with a low around 25. East northeast wind around 5 mph.
  datetime: '2023-12-02T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: cloudy
  wind_bearing: 67.5
  temperature: 25
  dew_point: 27
  wind_speed: 5
  humidity: 100
- detailed_description: >-
    A chance of snow before 5pm. Cloudy. High near 32, with temperatures falling
    to around 30 in the afternoon. North northeast wind 5 to 8 mph. Chance of
    precipitation is 50%. New snow accumulation of less than one inch possible.
  datetime: '2023-12-03T06:00:00-06:00'
  precipitation_probability: 50
  is_daytime: true
  condition: snowy
  wind_bearing: 22.5
  temperature: 32
  dew_point: 28
  wind_speed: 6.5
  humidity: 96
- detailed_description: Mostly cloudy, with a low around 22. North northwest wind around 5 mph.
  datetime: '2023-12-03T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: cloudy
  wind_bearing: 337.5
  temperature: 22
  dew_point: 26
  wind_speed: 5
  humidity: 100
- detailed_description: Mostly sunny, with a high near 37. West wind around 6 mph.
  datetime: '2023-12-04T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: partlycloudy
  wind_bearing: 270
  temperature: 37
  dew_point: 24
  wind_speed: 6
  humidity: 98
- detailed_description: >-
    A chance of snow showers. Mostly cloudy, with a low around 23. Chance of
    precipitation is 30%.
  datetime: '2023-12-04T18:00:00-06:00'
  precipitation_probability: 30
  is_daytime: false
  condition: snowy
  wind_bearing: 135
  temperature: 23
  dew_point: 25
  wind_speed: 6
  humidity: 100
- detailed_description: Mostly cloudy, with a high near 37.
  datetime: '2023-12-05T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 0
  temperature: 37
  dew_point: 28
  wind_speed: 8
  humidity: 98
- detailed_description: Mostly cloudy, with a low around 23.
  datetime: '2023-12-05T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: cloudy
  wind_bearing: 315
  temperature: 23
  dew_point: 26
  wind_speed: 9
  humidity: 94
- detailed_description: >-
    A slight chance of snow showers after noon. Mostly cloudy, with a high near
    36.
  datetime: '2023-12-06T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: snowy
  wind_bearing: 247.5
  temperature: 36
  dew_point: 25
  wind_speed: 10
  humidity: 93
- detailed_description: >-
    A slight chance of snow showers before midnight. Mostly cloudy, with a low
    around 26.
  datetime: '2023-12-06T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: snowy
  wind_bearing: 202.5
  temperature: 26
  dew_point: 28
  wind_speed: 12
  humidity: 97
- detailed_description: Partly sunny, with a high near 41.
  datetime: '2023-12-07T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 180
  temperature: 41
  dew_point: 32
  wind_speed: 9
  humidity: 96
- detailed_description: Mostly cloudy, with a low around 28.
  datetime: '2023-12-07T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: cloudy
  wind_bearing: 225
  temperature: 28
  dew_point: 31
  wind_speed: 10
  humidity: 100
- detailed_description: Mostly cloudy, with a high near 41.
  datetime: '2023-12-08T06:00:00-06:00'
  precipitation_probability: 0
  is_daytime: true
  condition: cloudy
  wind_bearing: 270
  temperature: 41
  dew_point: 36
  wind_speed: 12
  humidity: 100
- detailed_description: A slight chance of rain showers. Mostly cloudy, with a low around 28.
  datetime: '2023-12-08T18:00:00-06:00'
  precipitation_probability: 0
  is_daytime: false
  condition: rainy
  wind_bearing: 315
  temperature: 28
  dew_point: 33
  wind_speed: 13
  humidity: 100

attribution: Data from National Weather Service/NOAA
friendly_name: KIMT Daynight
supported_features: 6
```
